---
title: "p8105_hw5_yl4358"
author: "YI LIU"
date: "11/10/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme_bw() + theme(legend.position = "bottom"))
```

# Problem 1

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

replace_iris_na = function(x_arg){
  if (is.numeric(x_arg)) {
   x_arg = replace(x_arg, is.na(x_arg), mean(x_arg,na.rm = TRUE))
  } else {
   x_arg = replace(x_arg, is.na(x_arg), "virginica") 
  }
}

output_iris = vector("list", length = 5)

for (i in 1:5) {
  
  output_iris[[i]] = replace_iris_na(x_arg = iris_with_missing[[i]])
}

final_iris = bind_cols(output_iris)
final_iris %>% 
 head(10) %>% 
  knitr::kable(digits = 2) 


output_iris_map = map_df(iris_with_missing, replace_iris_na)

output_iris_map %>% 
 head(10) %>% 
  knitr::kable(digits = 2) 

```


# Problem 2

```{r}
long_df = tibble(
  file_names = list.files(path = "./data"),
  file_path = str_c("./data/", file_names)
  ) %>% 
  mutate(
    observation_df = map(file_path, read_csv)
  ) %>% 
  unnest() %>% 
  select(-file_path) %>% 
  separate(col = file_names, into = c("arm", "subject_id"), sep = "_") %>%
  mutate(
    arm = recode(arm, "con" = "control" , "exp" = "experimental"),
    subject_id = str_replace(subject_id, ".csv", " ")
  ) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "observation"
  )
  

long_df %>% 
  group_by(arm,subject_id) %>% 
  ggplot(aes(x = week, y = observation, group = subject_id, color = subject_id)) +
  geom_line() +
  labs(
    title = "Observation on each subject overtime",
    x = "Week",
    y = "Observation"
     ) +
  facet_grid(.~arm)
```

* The obeservation in experimental group is increasing overtime while the observation in control group is stable. The obeservation in experimental group is relative higher than that in control group.

# Problem 3

## Conduct simulation when beta1=0

```{r}
sim_regression = function(beta1) {
  
  sim_data = tibble(
    x = rnorm(30, mean = 0, sd = 1),
    y = 2 + beta1 * x + rnorm(30, 0, sqrt(50))
  )
  
ls_fit = 
  lm(y ~ x, data = sim_data) %>% 
   broom::tidy() 
tibble(
  beta1_hat = ls_fit[[2]][2],
  p_value = ls_fit[[5]][2]
)
}

output_beta10 = 
  rerun(10000, sim_regression(beta1 = 0)) %>% 
  bind_rows()
output_beta10 %>%
  head(10)
```

## Conduct a simulation to explore power in a simple linear regression

```{r}

```

